apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-chart
  namespace: {{ .Values.namespace }}
  labels:
    app: demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: ngnix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
       #   env:
       #     - name: PASSWORD
       #       valueFrom:
       #          secretKeyRef:
       #               key: password
       #               name: demopass
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http


      
