apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: {{ .Values.namespace }}
  labels:
    app: demo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo
